apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: infra
  labels:
    infra: zookeeper
spec:
  ports:
  - port: 2181
    name: client
  selector:
    infra: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zk
  namespace: infra
  labels:
    infra: zookeeper
spec:
  ports:
  - port: 2888
    name: peer
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    infra: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: exhibitor
  namespace: infra
  labels:
    infra: zookeeper
spec:
  ports:
  - port: 8181
    name: exhibitor
    nodePort: 30503
  type: NodePort
  selector:
    infra: zookeeper
